issue_tracker/config/routes.rb
IssueTracker::Application.routes.draw do

  get "tickets/search"
  post "tickets/answer" => "tickets#answer"
  resources :tickets
  devise_for :users
  get "users/index"

  root 'tickets#new'

  namespace :admin do
    resources :users, :tickets, :customers, :departments
  end

end

issue_tracker/app/models/answer.rb
class Answer < ActiveRecord::Base
end

issue_tracker/app/models/customer.rb
class Customer < ActiveRecord::Base
end

issue_tracker/app/models/department.rb
class Department < ActiveRecord::Base
end

issue_tracker/app/models/status.rb
class Status < ActiveRecord::Base
end

issue_tracker/app/models/ticket.rb
class Ticket < ActiveRecord::Base

  # WAITING_FOR_STAFF_RESPONSE = 0
  # WAITING_FOR_CUSTOMER = 1
  # ON_HOLD = 2
  # CANCELLED = 3
  # COMPLETED = 4
  before_create do
    self.status = 1
    self.unique = random_string+random_number+random_string+random_number+random_string
  end
  def random_string
    o = [('A'..'Z')].map { |i| i.to_a }.flatten
    ((0...3).map { o[rand(o.length)] }.join)
  end
  def random_number
    '-'+(rand(899)+100).to_s+'-'
  end
end

issue_tracker/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  STAFF_USER = 0
  ADMIN_USER = 1
end

issue_tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    if user_signed_in?
    if current_user.accaunt_type == User::ADMIN_USER
      redirect_to admin_users_path
    else
      redirect_to users_index_url
    end
      end
  end
end

issue_tracker/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.order(:status)
    init_models
  end

  def search
    # Searching ticket by id
    @ticket = Ticket.find_by(unique: params[:id])
    if @ticket.nil?
      @tickets = Ticket.where("lower(text) LIKE ?", "%#{params[:id].downcase}%")
      if @tickets.nil?
        redirect_to new_ticket_path, notice: 'Ticket not found'
      else
        init_models
        @notice = 'Found those tickets:'
        render 'index'
      end
    else
      @answers = Answer.where(ticket_id: @ticket.id)
      render 'show'
    end
  end

  def answer
    @answer = Answer.new(answer_params)
    @answer.save
    @ticket = Ticket.find(@answer.ticket_id)
    UserMailer.answer(@ticket, @answer).deliver
    redirect_to @ticket
  end
  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @status = Status.find(@ticket.status)
    @user = User.find_by(@ticket.ownership)
    @department = Department.find_by(@ticket.department)
    @customer = Customer.find(@ticket.customer_id)
    @answers = Answer.where(ticket_id: @ticket.id)
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket.department = 1
    @department = Department.all
  end

  # GET /tickets/1/edit
  def edit
    @department = Department.all
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @customer = Customer.find_or_create_by(email: params[:email])
    @customer.name = params[:name]
    @customer.save

    @ticket.department = params[:department]
    @ticket.customer_id = @customer.id
    respond_to do |format|
      if @ticket.save
        UserMailer.new_ticket_email(@customer, @ticket).deliver
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    @ticket.department = params[:department]
    respond_to do |format|
      if @ticket.update(ticket_params)
        UserMailer.change_ticket(@ticket).deliver
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:subject, :text, :department, :status, :ownership, :customer_id, :unique)
    end

    def answer_params
      params.require(:answer).permit(:text, :ticket_id)
    end

    def init_models
      @statuses = Status.all
      @users = User.all
      @departments = Department.all
      @customers = Customer.all
    end
end

issue_tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @data = Ticket.all
  end
end

issue_tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

issue_tracker/app/helpers/tickets_helper.rb
module TicketsHelper
end

issue_tracker/app/helpers/users_helper.rb
module UsersHelper
end

issue_tracker/app/views/application/index.html.haml
%h1 Welcome
%p Create Yours ticket by button on top
-#= form_for Ticket do |f|
-#  = f.text_field (:search , class: "form-control")

issue_tracker/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Issue Tracker
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "#"} Brand
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          -#%ul.nav.navbar-nav
          -#  %li.active
          -#    %a{href: "#"} Link
          -#  %li
          -#    %a{href: "#"} Link
          -#  %li.dropdown
          -#    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
          -#      Dropdown
          -#      %span.caret
          -#    %ul.dropdown-menu{role: "menu"}
          -#      %li
          -#        %a{href: "#"} Action
          -#      %li
          -#        %a{href: "#"} Another action
          -#      %li
          -#        %a{href: "#"} Something else here
          -#      %li.divider
          -#      %li
          -#        %a{href: "#"} Separated link
          -#      %li.divider
          -#      %li
          -#        %a{href: "#"} One more separated link
          -#= form for
          %form.navbar-form.navbar-left{role: "search", action: tickets_search_path}
            .form-group
              %input.form-control{name: "id", placeholder: "Search", type: "text"}/
            %button.btn.btn-default{type: "submit"} Submit
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'New ticket', new_ticket_path
            - unless user_signed_in?
              %li= link_to 'Sign in', user_session_path
            - else
              %li= link_to 'All tickets', tickets_path
              %li= link_to current_user.email
              %li= link_to 'Logout', destroy_user_session_path, :method => :delete

            -#%li.dropdown
            -#  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            -#    Dropdown
            -#    %span.caret
            -#  %ul.dropdown-menu{role: "menu"}
            -#    %li
            -#      %a{href: "#"} Action
            -#    %li
            -#      %a{href: "#"} Another action
            -#    %li
            -#      %a{href: "#"} Something else here
            -#    %li.divider
            -#    %li
            -#      %a{href: "#"} Separated link
    .container
      - unless notice.nil?
        %p.notice= notice
      - unless alert.nil?
        %p.alert= alert

      = yield

issue_tracker/app/views/tickets/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for @ticket do |f|
      - if @ticket.errors.any?
        #error_explanation
          %h2= "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
          %ul
            - @ticket.errors.full_messages.each do |msg|
              %li= msg
      .panel.panel-info
        .panel-heading
          %h3.panel-title
          .field
            = f.label :subject
            = f.text_field :subject, class: "form-control"
        .panel-body
          .field
            = f.label :text
            = f.text_area :text, class: "form-control"
          .field
            = f.label 'Select department'
            = select_tag "department", options_from_collection_for_select(@department, "id", "name", @ticket.department), {class: "form-control"}
        .panel-footer
          .field
            = f.label 'Enter Your name'
            = text_field_tag 'name', "", class: "form-control"
          .field
            = f.label 'Enter Your email'
            = text_field_tag 'email', "", class: "form-control"
            -#= f.text_field :department
          -#.field
          -#  = f.label :status
          -#  = f.text_field :status
          -#.field
          -#  = f.label :ownership
          -#  = f.text_field :ownership
          -#.field
          -#  = f.label :customer_id
          -#  = f.text_field :customer_id
          -#.field
          -#  = f.label :unique
          -#  = f.text_field :unique
          .actions
            = f.submit 'Save', class: "btn"

issue_tracker/app/views/tickets/answer.html.haml
%h1 Ticket#answer
%p Find me in app/views/ticket/answer.html.haml

issue_tracker/app/views/tickets/create.html.haml
%h1 Ticket#create
%p Find me in app/views/ticket/create.html.haml

issue_tracker/app/views/tickets/edit.html.haml
%h1 Editing ticket

= render 'form'

= link_to 'Show', @ticket
\|
= link_to 'Back', tickets_path

issue_tracker/app/views/tickets/getTicker.html.haml
%h1 Ticket#getTicker
%p Find me in app/views/ticket/getTicker.html.haml

issue_tracker/app/views/tickets/index.html.haml
%h1 Listing tickets

%table.table.table-striped.table-bordered
  %tr
    %th Subject
    %th Text
    %th Department
    %th Status
    %th Ownership
    %th Customer
    %th Unique
    %th
    %th
    %th
  - status = -1
  - @tickets.each do |ticket|
    - if status != ticket.status
      - status = ticket.status
      %tr.success
        %td{"colspan"=>"10"}= @statuses.find(ticket.status).name
    %tr
      %td= ticket.subject
      %td= ticket.text
      %td
        - unless ticket.department.nil?
          = @departments.find(ticket.department).name
      %td
        = select_tag "status_#{ticket.id}", options_from_collection_for_select(@statuses, "id", "name", ticket.status), { :class => 'form-control' }
        %button.btn.btn-default{"onclick" => "setStatus(#{ticket.id})"} Set
      %td
        = select_tag "ownership_#{ticket.id}", options_from_collection_for_select(@users, "id", "name", ticket.ownership), { :class => 'form-control' }
        %button.btn.btn-default{"onclick" => "setOwnership(#{ticket.id})"} Set
      %td= @customers.find(ticket.customer_id).name
      %td= ticket.unique
      %td
        %button.btn.btn-default{"onclick" => "giveAnswer(#{ticket.id})"} Give answer
      %td= link_to 'Show', ticket
      %td= link_to 'Edit', edit_ticket_path(ticket)
      -#%td= link_to 'Destroy', ticket, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ticket', new_ticket_path

#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      = form_for(:answer, :url => {:action => 'answer'}, :method => :post) do |f|
        .modal-header
          %button.close{"data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h4.modal-title Enter answer
        .modal-body
          %p
            = text_area(:answer, :text, rows: 10, class: "form-control")
            = hidden_field(:answer, :ticket_id)
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
          %button.btn.btn-primary{type: "submite"} Save answer

issue_tracker/app/views/tickets/new.html.haml
%h1 Use search by ticket id or words in top or create new ticket

= render 'form'

-#= link_to 'Back', tickets_path

issue_tracker/app/views/tickets/show.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-info
      .panel-heading
        %h3.panel-title
          Subject:
          = @ticket.subject
      .panel-body
        %p
          %b Text:
          = @ticket.text
        - unless @department.nil?
          %p
            %b
              Department:
              = @department.name
        %p
          %b Status:
          = @status.name
        %p
          %b Ownership:
          = @user.name
        %p
          %b Customer name:
          = @customer.name
        %p
          %b Customer email:
          = @customer.email
        %p
          %b Unique:
          = @ticket.unique

        = link_to 'Edit', edit_ticket_path(@ticket)
        \|
        = link_to 'Back', tickets_path
      - unless @answers.nil?
        .panel-footer
          Answers:
        %ul.list-group
          - @answers.each do |answer|
            %li.list-group-item= answer.text

issue_tracker/app/views/tickets/update.html.haml
%h1 Ticket#update
%p Find me in app/views/ticket/update.html.haml

issue_tracker/app/views/users/index.html.haml
.col-md-3
  .panel.panel-default
    .panel-heading
      %h3.panel-title New unassigned tickets
    .panel-body
      Panel content
    %ul.list-group
      %li.list-group-item Cras justo odio
.col-md-3
  .panel.panel-default
    .panel-heading
      %h3.panel-title Open Tickets
    .panel-body
      Panel content
.col-md-3
  .panel.panel-default
    .panel-heading
      %h3.panel-title On hold tickets
    .panel-body
      Panel content
.col-md-3
  .panel.panel-default
    .panel-heading
      %h3.panel-title Closed Tickets
    .panel-body
      Panel content